name: tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  pytest:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Cache environment
        uses: actions/cache@master
        id: cache
        with:
          path: ${{ env.pythonLocation }}/lib/python3.8/site-packages/*
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install -e .[dev]

      - name: Run Docstr-Coverage
        run: docstr-coverage src tests  -e  ".*/src/fundus/publishers"