# This release workflow was created using the following guide
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  release:
    types:
      - released

jobs:

  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check version matches tag
        run: |
          pip install tomli
          TAG="${{ github.event.release.tag_name }}"
          PACKAGE_VERSION=$(python3 -c "
          import tomli
          with open('pyproject.toml', 'rb') as f:
            print(tomli.load(f)['project']['version'])
          ")
          if [[ "$TAG" != "$PACKAGE_VERSION" ]]; then
            echo "Tag ($TAG) does not match package version ($PACKAGE_VERSION)"
            exit 1
          fi

  test:
    needs: check-version
    name: Test the latest release commit
    uses: ./.github/workflows/tests.yml

  lint:
    needs: check-version
    name: Lint the latest release commit
    uses: ./.github/workflows/ruff.yml

  build:
    name: Build distribution 📦
    needs:
      - test
      - lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/fundus
      
    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true


      - name: Sleep for 2 minutes
        run: sleep 2m
        shell: bash

  test-distribution:
    name: Install and test TestPyPi distribution
    needs:
      - publish-to-testpypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install package
        run: >-
          python3 -m 
          pip install 
          --index-url https://test.pypi.org/simple/ 
          --extra-index-url https://pypi.org/simple/ 
          fundus==${{ github.event.release.tag_name }}

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs:
      - test-distribution
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/fundus

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

